version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      LOG_PATH: /app/logs
      STORAGE_PATH: /app/storage
      DATASOURCE_JDBC_URL: jdbc:mariadb://database:${MYSQL_PORT}/${MYSQL_DATABASE}
      DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      ORACLE_DATASOURCE_JDBC_URL: jdbc:oracle:thin:@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE_NAME}
      ORACLE_DATASOURCE_USERNAME: ${ORACLE_USERNAME}
      ORACLE_DATASOURCE_PASSWORD: ${ORACLE_PASSWORD}
      BANKID_CLIENT_ID: ${BANKID_CLIENT_ID}
      BANKID_CLIENT_SECRET: ${BANKID_CLIENT_SECRET}
      BANKID_REDIRECT_URI: ${BANKID_REDIRECT_URI}
      ALEPH_SERVICE_HOST: ${ALEPH_SERVICE_HOST}
      ALEPH_SERVICE_PORT: ${ALEPH_SERVICE_PORT}
      ALEPH_SERVICE_REST_API_URI: ${ALEPH_SERVICE_REST_API_URI}
      ALEPH_SERVICE_WWWUSER: ${ALEPH_SERVICE_WWWUSER}
      ALEPH_SERVICE_WWWPASSWD: ${ALEPH_SERVICE_WWWPASSWD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS: ${MAIL_SMTP_STARTTLS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    volumes:
      - ./../../:/app
      - ./../../.m2:/root/.m2
      - ./../../logs:/app/logs
      - ./../../storage:/app/storage
    working_dir: /app
    command: sh ./.docker/testing/run.sh
    ports:
      - ${APP_PORT_HOST}:${APP_PORT}
    depends_on:
      - database
    networks:
      - spring-network

  database:
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-network

volumes:
  db-data:

networks:
  spring-network:
    driver: bridge