version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      LOG_PATH: /app/logs
      DATASOURCE_JDBC_URL: jdbc:mariadb://database:${MYSQL_PORT}/${MYSQL_DATABASE}
      DATASOURCE_USERNAME: ${MYSQL_USER}
      DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      BANKID_CLIENT_ID: ${BANKID_CLIENT_ID}
      BANKID_CLIENT_SECRET: ${BANKID_CLIENT_SECRET}
    volumes:
      - ./../../:/app
      - ./../../.m2:/root/.m2
      - ./../../logs:/app/logs
    working_dir: /app
    command: sh ./.docker/local/run.sh
    ports:
      - ${APP_PORT_HOST}:${APP_PORT}
      - 35729:35729
      - 5005:5005
    depends_on:
      - database
    networks:
      - spring-network

  database:
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT_HOST}:${MYSQL_PORT}
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT_HOST}:${PHPMYADMIN_PORT}
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - spring-network

volumes:
  db-data:

networks:
  spring-network:
    driver: bridge